name: Indentation and Formatting Check

on: [push, pull_request]

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Prettier
      run: npm install prettier

    - name: Check Formatting
      run: npx prettier --check . --ignore-path .gitignore
