name: Indentation and Formatting Check and Fix

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Prettier
      run: npm install prettier

    - name: Auto-fix Formatting
      run: npx prettier --write .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Automatically fix code formatting" || echo "No changes to commit"
        git push